### ISSUE TITLE
erlim_session problem

### ISSUE THREAD

**Issue by wudixiaotie** [FlowerWrong/erlim#1]
If you want to spawn lots of worker process of a gen_server  module. You must not named it.
[Your Code Here](https://github.com/FlowerWrong/erlim/blob/master/src/erlim_session.erl#L39) need to change like this

``` erlang
gen_server:start_link(?MODULE, [Socket], []).
```

That is why you use supervisor:start_child alway failed at the second time, beause the first time one child process already registered as name "erlim_session".

**Comment by FlowerWrong** [comment]
@wudixiaotie Thanks very much.
